language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t yadhus/docker-simple -f Dockerfile.dev .

script:
  - docker run -e CI=true yadhus/docker-simple npm run test

deploy:
  provider: script
  script: >-
    docker login --username=$HEROKU_EMAIL --password=$HEROKU_PASSWORD registry.heroku.com
    docker build registry.heroku.com/rocky-bayou-95129/web
    docker push registry.heroku.com/rocky-bayou-95129/web
