language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  #   - docker build -t yadhus/docker-simple -f Dockerfile.dev .
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com

# script:
#   - docker run -e CI=true yadhus/docker-simple npm run test

script:
  - docker build -t yadhus/docker-simple .
  - docker tag yadhus/docker-simple registry.heroku.com/rocky-bayou-95129/web

deploy:
  provider: script
  script: >-
    docker push registry.heroku.com/rocky-bayou-95129/web
    heroku container:release web -a rocky-bayou-95129
  on:
    branch: master
