language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t yadhus/docker-simple -f Dockerfile.dev .

script:
  - docker run -e CI=true yadhus/docker-simple npm run test

deploy:
  provider: heroku
  api_key:
    secure: 5b039a59-9314-41a5-bcc4-dc668dac8e0e
  app: rocky-bayou-95129
  on:
    branch: master
