language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  #   - docker build -t yadhus/docker-simple -f Dockerfile.dev .
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - docker login --username=$HEROKU_EMAIL --password=$HEROKU_PASSWORD registry.heroku.com

# script:
#   - docker run -e CI=true yadhus/docker-simple npm run test

script:
  - docker build -t yadhus/docker-simple .
  - docker tag yadhus/docker-simple registry.heroku.com/rocky-bayou-95129/web
  - docker push registry.heroku.com/rocky-bayou-95129/web

deploy:
  provider: script
  script: docker run --rm -e HEROKU_API_KEY=$HEROKU_PASSWORD registry.heroku.com/rocky-bayou-95129/web container:release web --app rocky-bayou-95129
  on:
    branch: master
